services:
  - type: web
    name: resume-analyzer
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: XAI_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DATABASE_URL
        fromDatabase:
          name: resume-analyzer-db
          property: connectionString
      - key: FLASK_APP
        value: main.py

databases:
  - name: resume-analyzer-db
    databaseName: resume_analyzer
    plan: free