services:
  - type: web
    name: resume-analyzer
    env: python
    buildCommand: "poetry install"
    startCommand: "gunicorn --bind 0.0.0.0:\$PORT --workers=2 main:app"
    envVars:
      - key: XAI_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DATABASE_URL
        fromDatabase:
          name: resume-analyzer-db
          property: connectionString
      - key: FLASK_APP
        value: main.py

databases:
  - name: resume-analyzer-db
    databaseName: resume_analyzer
    plan: free
